# Generated by Django 4.2.5 on 2023-09-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentquery_currunt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquery',
            name='currunt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 22, 48, 18, 978906)),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='curuunt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 22, 48, 18, 978906)),
        ),
    ]
