# Generated by Django 4.2.5 on 2023-09-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teachersignup_delete_studentsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignup',
            name='curuunt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 22, 48, 18, 979904)),
        ),
    ]
